name: IWYU Analysis

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.22.x'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Install iwyu
      run: |
        sudo apt-get update
        sudo apt-get install -y iwyu

    - name: Register problem matcher
      run: echo "::add-matcher::./.github/problem-matcher.json"

    - name: Export CXXFLAGS
      run: |
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON executables/referenceApp
        export CXXFLAGS="-isystem /usr/lib/llvm-17/lib/clang/17/include/"
        echo "done exporting"
        python3 iwyu_tool.py -p compile_commands.json

    - name: Unregister problem matcher
      if: always()
      run: echo "::remove-matcher owner=iwyu-matcher::"
